Structural patterns
SiarheiBarkouski/Patterns pull request #2
Opened 2018-01-19 11:47 UTC by SiarheiBarkouski

StructuralPatterns done.

2018-01-20 20:41 UTC, MaksimNikitin requested changes
Nice job, Siarhei! Fix some cosmetic remarks and the PR will be approved. 
Remember to ping me after fixing them.

2018-01-20 20:41 UTC, MaksimNikitin commented on StructuralPatterns/Adapter/StringAdapter.cs
> +            set => _inputString = value;
You could try ti get rid of the filed and make the property auto. Intitializing form the cinstructor should work fine as well.

2018-01-20 20:41 UTC, MaksimNikitin commented on StructuralPatterns/Adapter/StringAdapter.cs
> +            int counter = 0;
using of var is preferable

2018-01-20 20:41 UTC, MaksimNikitin commented on StructuralPatterns/Adapter/StringAdapter.cs
> +                counter += _inputString.Count(t => t.Equals(letters[i]));
Your method is supposed to return just a number. Do not need to display anything on console, it should be program.cs responcibility.

2018-01-20 20:41 UTC, MaksimNikitin commented on StructuralPatterns/Facade/DifficultMathOperations.cs
> +        public double Log(int a)
The same thing as in the previous PR. Rework names of your methods.

2018-01-20 20:41 UTC, MaksimNikitin commented on StructuralPatterns/Adapter/StringAdapter.cs
> +                counter += _inputString.Count(t => t.Equals(letters[i]));
By the way, foreach in this case would look better.

2018-01-22 14:55 UTC, SiarheiBarkouski commented
I modified the project. Pls, have a look at it.
@MaksimNikitin

2018-01-24 16:30 UTC, MaksimNikitin approved these changes

2018-01-25 06:00 UTC, merged